sudo: required
dist: trusty
services: docker
script:
- docker run --rm -v $(pwd):/data -it blang/latex:ctanfull latexmk -cd -lualatex -bibtex -silent -f --synctex=1
deploy:
  provider: releases
  api_key:
    secure: MtZWBSZ4uGl1LwTpclDYjT3zreJ/M5QX+OiJcQBOER70FY8Yv0HJZBKAWf/qOeOX//eJJRHZTmIoChku217F2psxSfI0NuGN4vbqZ3w2zjqhxZdeJb+2pADZ/XBCQbCPOuUMr6OqCFMdyvUb6BX8rTATYoY4HIfamxu6taYGSCzhXjcfxcGA8XDPmPorcxDBILIezEcnFUKRjodvEeaYVzrHNF0kYFHQLmP0xS+dQaaP797oA4gdfO4NgQIr15x+p4QSWnY5IGfyOr5BWiA9u1fANroq3L/XzFrGEquHX3RtLyRGKVx+j7Cfenrep1SfYi6ePtA56+/5XBA752yX8JI1FwsPfUuHFktMklz9xTqHuCljfr6Fd9nWwypIGZH2OZrV6MKDx80G9OcnhApxvvhgHd6gHL028YMkBIRDrlGaKjMQrD+jLRONfs8NXoTQv+TfKTnDPSpBOvSGECEwz2Zhe9UGfTz6wzJdgAli8t0RNnqPyARiXPgzPxYdOagNScJOFSONHWTawipK4uQC4a9s9X2il0aCAte90QP9SGVb8x5PAuTQYHHz20thOigsGFepHOLmKAcblzZkh3QPDNfMCP3xmyxTxzAMzx1V+UMKzeFH9XkeHsuhO5RRcUXMGLZ6Y22gPNcA7FvnlQyZ2lNfWhSvP9o4KVZKEokQyMc=
  file: lcDetectorRnD.pdf
  skip_cleanup: true
  on:
    repo: linearcollider/DetectorLiaisonReport
    tags: true
